Benchmark generator & template-heavy benchmark
Polymer/lit-html pull request #1318
Opened 2020-09-25 02:44 UTC by kevinpschaaf

Adds a generalized template benchmark generator, and adds a generated `template-heavy` benchmark for lit-html to CI.

For running the generator standalone:
* `npm run generator -- -t` will run generate a default configuration across all supported renderers (lit-html, idom, react, preact) and compare them in tachometer
* `npm run generator -- --help` for full options

The `template-heavy` benchmark for lit-html:
* `npm run benchmark:lit-heml:template-heavy` to run locally
* `npm run regen-template-benchmarks` to the benchmark as checked-in

2020-10-07 18:26 UTC, sorvell requested changes

2020-10-07 18:26 UTC, sorvell commented on packages/benchmarks/generator/src/index.ts
> +        if (depthForLevel(level) < opts.depth) {
Hard to follow the code past here. Some comments would be helpful.

2020-10-08 18:35 UTC, kevinpschaaf commented on packages/benchmarks/generator/src/deoptigate.ts
> +  await new Promise(r => setTimeout(() => r(), 2000));
Eh, I just didn't want to implement a polling thing to know when the benchmark was done or the page had settled.

2020-10-08 18:38 UTC, kevinpschaaf commented on packages/benchmarks/generator/src/renderers.ts
> +  const idomKeyedStaticsRenderer: TemplateRenderer = {
In incremental DOM, you can differentiate "static" attributes from dynamic ones and just specify them once, and then you don't have to call `attr` on every render for them, but that also requires keying the nodes. I just did that mode as a separate renderer so we could evaluate the benefit of that optimziation.

http://google.github.io/incremental-dom/#statics-array

2020-10-09 23:19 UTC, sorvell approved these changes

2020-10-09 23:51 UTC, merged