[lit-next] Adds UpdatingController
Polymer/lit-html pull request #1405
Opened 2020-11-02 18:30 UTC by sorvell

Adds `UpdatingController`, a class which can interact with an `UpdatingElement` by hooking into its lifecycle, including connected, disconnected, update, updated, and requestUpdate.

2020-11-06 09:54 UTC, daKmoR commented
this is going to be soooo useful 🤗

thaaankks 🙇‍♂️

2020-11-07 00:01 UTC, kevinpschaaf requested changes

2020-11-07 00:11 UTC, sorvell commented on packages/labs/src/controllers/updating-controller.ts
> +  updated(_changedProperties: PropertyValues) {}
Following the convention used in UpdatingElement where you can safely call the `super` version (even though you don't have to).

2020-11-07 00:30 UTC, sorvell commented on packages/labs/docs/CONTROLLERS.md
> +Can be used to calculate derived state using element state. Note, this will be called during server rendering and therefore should not access element DOM.
Tracked via https://github.com/Polymer/lit-html/issues/1417

2020-11-07 02:06 UTC, sorvell commented on packages/labs/src/index.ts
> +export * from './controllers/updating-controller.js';
Done.

2020-11-07 02:09 UTC, sorvell commented on packages/benchmarks/lit-element/list/index.ts
> +  await new Promise((r) => setTimeout(r));
Done

2020-11-07 02:10 UTC, sorvell commented on packages/labs/docs/CONTROLLERS.md
> +  _interval;
Done

2020-11-07 02:11 UTC, sorvell commented on packages/labs/docs/CONTROLLERS.md
> +Classes have a constructor which can be used as usual for initialization. Controllers can be factory functions as well.
Clarified.

2020-11-07 02:12 UTC, sorvell commented on packages/labs/docs/CONTROLLERS.md
> +Can be used to add global event listeners, or fire events for a context API.
Clarified.

2020-11-07 02:17 UTC, sorvell commented on packages/labs/docs/CONTROLLERS.md
> +  }
Added section in doc about exploring an `@property` feature.

2020-11-30 20:04 UTC, sorvell commented
Closing in favor of https://github.com/Polymer/lit-html/pull/1435

2020-11-30 20:04 UTC, closed without merging