Generate separate prettier and eslint ignore files to improve auto-formatting behavior
Polymer/lit-html pull request #1414
Opened 2020-11-03 19:36 UTC by aomarks

We want to avoid formatting and linting all Git-ignored files, plus a few additional patterns. However, neither Prettier [1] nor ESLint [2] support passing multiple ignore files. So, we now instead maintain separate `.prettierignore` and `.eslintignore` files, but automatically inject the contents of `.gitignore` into them.

This replaces the previous hacky approach, where I was creating a temp file before formatting/linting. This was bad because 1) it didn't work with our husky auto-format hook, and 2) it didn't work with the VSCode Prettier plugin.

Also creates a `.vscode/settings.json` for each sub-package to tell the VSCode Prettier plugin which ignore file to use.  By default it looks in the root of each sub-package, and finds no `.prettierignore` file. This way, format-on-save in VSCode will automatically respect our rules.

[1] https://github.com/prettier/prettier/issues/8048
[2] https://github.com/eslint/eslint/issues/9794

cc @abdonrd

2020-11-04 09:40 UTC, abdonrd requested changes

2020-11-04 09:43 UTC, abdonrd commented
@aomarks thinking about this... I want to propose this alternative, which is a bit more declarative and easy to maintain.

https://github.com/Polymer/lit-html/pull/1415/files

2020-11-05 20:27 UTC, aomarks commented on lit-next.code-workspace
> +		"files.trimTrailingWhitespace": true
Removed (though I like it as a default for files that aren't auto-formatted).

2020-11-05 20:27 UTC, aomarks commented on lit-next.code-workspace
> +			"esbenp.prettier-vscode",
Done.

2020-11-05 20:27 UTC, aomarks commented
> @aomarks thinking about this... I want to propose this alternative: #1415
> Which seems a bit more declarative and easy to maintain.

Thanks, merged.

2020-11-05 21:45 UTC, abdonrd commented
With this #1415, are the `.vscode/settings.json` files still needed?

2020-11-05 21:54 UTC, aomarks commented
> With this #1415, are the `.vscode/settings.json` files still needed?

Yeah, the prettier extension is a bit weird and looks for a `.prettierrc` in each root of a multi-root workspace, instead of looking for the nearest `.prettierrc` on disk, like I would expect.

2020-11-10 16:58 UTC, justinfagnani approved these changes

2020-11-10 17:08 UTC, merged