[labs] WIP: useController hook in labs
Polymer/lit-html pull request #1532
Opened 2021-01-13 03:36 UTC by justinfagnani

This is just a rough sketch at the moment.

2021-02-25 18:56 UTC, sorvell commented
@justinfagnani Can you rebase this against the current lit-next? That'll make it easier to review.

2021-03-15 20:46 UTC, justinfagnani commented
@sorvell this is all rebased and cleaned up now!

2021-04-15 17:21 UTC, sorvell requested changes

2021-04-15 17:21 UTC, sorvell commented on packages/labs/react/src/use-controller.ts
> +  // useMemo() because React does not gaurentee that it will preserve values
```suggestion
  // useMemo() because React does not guarantee that it will preserve values
```

2021-04-15 17:21 UTC, sorvell commented on packages/labs/react/src/use-controller.ts
> +  // We use useLayoutEffect because we need update() called synchronously
```suggestion
  // We use useLayoutEffect because we need updated() called synchronously
```

2021-04-20 03:39 UTC, sorvell approved these changes

2021-04-20 03:40 UTC, merged