[lit-next] Prepare next pre-releases
Polymer/lit-html pull request #1608
Opened 2021-02-11 22:44 UTC by justinfagnani

2021-02-11 23:19 UTC, kevinpschaaf requested changes
Need to update the `litHtmlVersions` and friends right?

2021-02-11 23:35 UTC, justinfagnani commented
> Need to update the litHtmlVersions and friends right?

done

2021-02-12 00:05 UTC, sorvell approved these changes

2021-02-12 00:09 UTC, kevinpschaaf approved these changes
LGTM, small readme nit

2021-02-12 00:09 UTC, kevinpschaaf commented on README.md
> +- [`localize`](./packages/localize)
I guess if we're making the link text the npm package name, it should be
```suggestion
- [`@lit/localize`](./packages/localize)
```

2021-02-12 00:48 UTC, merged