[labs] Add @lit-labs/ssr-client and move renderLight
Polymer/lit-html pull request #1689
Opened 2021-03-23 06:54 UTC by kevinpschaaf

2021-03-30 22:25 UTC, sorvell requested changes
Just one nit. Are the package.json's for some of the other packages updated just for consistency? (maybe add to PR description?)

2021-03-30 22:25 UTC, sorvell commented on packages/labs/ssr-client/tsconfig.json
> +    "target": "es2020",
Should be es2019

2021-03-31 08:06 UTC, kevinpschaaf commented on packages/labs/ssr-client/tsconfig.json
> +    "target": "es2020",
Done

2021-03-31 12:51 UTC, sorvell approved these changes
LGTM

2021-03-31 17:14 UTC, merged