[lit-html] Add version-stability test
Polymer/lit-html pull request #1724
Opened 2021-04-02 22:36 UTC by kevinpschaaf

Adds a `version-stability-build` using a special rollup config that adds a `VERSION_TEST_` prefix to all non-stable mangled properties, and adds a `version-stability_test.js` that imports the normal `prod` build as well as the `version-stability-build` into the same test file, and tests various known stability-sensitive operations:
* `TemplateResult` passed to different-version `render`
* `nothing` & `noChange` passed to different-version `render`
* `Directive` passed to different-version `render`
* `Directive` passed to different version `Directive` (nested directives)
* `AsyncDirective` (with `disconnect`/`reconnect`) passed into a different-version `render`
* `repeat` directive (which makes its own parts using `directive-helpers`) passed into different-version `render`
* `AsyncDirective` passed to different version `repeat`

Note the test file is in JS not TS, as I found it exceedingly difficult to get a TS setup to build a test file in this package that works with builds in the same package like this.

2021-04-08 19:05 UTC, sorvell requested changes
Looks good with just a couple of nits. Is it worth parameterizing the repeated tests to ensure there aren't mistakes?

2021-04-08 19:05 UTC, sorvell commented on packages/lit-html/src/test/version-stability_test.js
> +const passthruB = directiveA(
directiveB?

2021-04-08 19:05 UTC, sorvell commented on packages/lit-html/src/test/version-stability_test.js
> +    await nextFrame();
```suggestion
    // Wait until directive updates value.
    await nextFrame();
```

2021-04-13 07:59 UTC, kevinpschaaf commented on packages/lit-html/src/test/version-stability_test.js
> +const passthruB = directiveA(
Done

2021-04-13 07:59 UTC, kevinpschaaf commented on packages/lit-html/src/test/version-stability_test.js
> +const asyncB = directiveA(
Done

2021-04-13 16:43 UTC, sorvell approved these changes

2021-04-13 22:39 UTC, merged